### PR TITLE
Restructure strdup definition

### PR DESCRIPTION
**Pull request by mrtazz**
I had problems compiling the library on OSX and FreeBSD as on both platforms strdup is already defined in string.h. This seems to be the case when using GCC. So I added some preprocessor defines to only use the custom strdup if _GNU_SOURCES is not defined. I also moved the strdup code into a single .h file for better maintenance as the same code existed in 3 locations.

I don't have a non GNU system with no strdup definition at hand to test the other case, but it works on OSX and FreeBSD for me now. I am not sure if there is a better solution (or more suitable #define to check for) as I am not a C programmer. So all input on this is very welcome.

### CODE REVIEW

**Comment by tonyg** [comment]
Wow. I'm _very_ surprised to see an implementation of `strdup()` in the code _at all_. `strdup()` is defined to exist in `string.h` by POSIX.1 and is present on Linux, OS X, and (as far as I know, given its 4.4BSD origins) every BSD. I'm curious as to why it appeared in the codebase to begin with -- is there some Windows thing I'm missing? If so, why isn't it solely in the Windows support code?

**Comment by mrtazz** [comment]
I discussed this with David from RabbitMQ and he also thinks that the `strdup()` implementation is not needed. It suffices to `#include "config.h"` as it defines `_GNU_SOURCE` and enables the platform version of it in `string.h`. The newly added commit reflects this.

**Comment by dpw** [comment]
Tony: Linux string.h doesn't always declare strdup.  Back when I was doing the ANSIfication of librabbitmq, I though it was reacting to something gcc was defining in response to -ansi -pedantic.  But it turns out that it was just because we were missing _GNU_SOURCE.

**Comment by dpw** [comment]
Looks good.  Daniel: As soon as we get the scan of the contributor agreement, I'll pull.

**Comment by tonyg** [comment]
Yeah, it's a POSIX.1 function, not an ANSI function, so presumably it was the `-ansi` flag getting its knickers in a twist. I can't say I'd recommend the `-ansi` flag, if it's going to do stupid things like that :-)

If you're looking for POSIX rather than GNU portability, you might prefer `-D_XOPEN_SOURCE=600` to `-D_GNU_SOURCE`.

**Comment by dpw** [comment]
Autoconf seems to default to putting _GNU_SOURCE in config.h.  I imagine you can configure it do something else, but it doesn't seem worth it.

**Pull request merged**
