### PR TITLE
CMake Build System

### PR DESCRIPTION
**Pull request by alanxz**
Created a cmake-based build system.

The benefit being it can be built just as easily on Windows (MSVC, MinGW), Linux and Mac.

First time sending a pull request to you, let me know if I should be going through a different channel.

### CODE REVIEW

**Comment by dpw** [comment]
With workarounds for those three issues, I've built under Linux, Visual Studio 10 and mingw/msys, and it looks good.  It will be great to have a proper visual studio build.

**Comment by alanxz** [comment]
The only other thing I can think of at this point is the ability for the user to choose whether to build a shared or static library. Right now it unconditionally creates a shared library.

**Comment by dpw** [comment]
I'm happy to merge without support for building static libs.  Static libs might be nice, but I guess support for them can easily be added later on.

**Comment by alanxz** [comment]
Ok. Go ahead an merge away!

**Comment by dpw** [comment]
Merged.  Because the changes had to go through our hg repo, the git commit IDs have changed in the merge process.

(I can sometimes get the commit IDs to round-trip through hg and stay the same, but in this case some commits had distinct authors and committers which hg doesn't understand.)

**Pull request closed without merging**
